/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppConfig: typeof import('./src/views/layout/AppConfig.vue')['default']
    AppConfigurator: typeof import('./src/views/layout/AppConfigurator.vue')['default']
    AppFooter: typeof import('./src/views/layout/AppFooter.vue')['default']
    AppLayout: typeof import('./src/views/layout/AppLayout.vue')['default']
    AppMenu: typeof import('./src/views/layout/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/views/layout/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/views/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/views/layout/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
